#!/usr/bin/env node
/**
 * Bundles the action into committed `dist/` files with every `node_modules`
 * dependency inlined, because GitHub runs the action straight from the repo (no
 * `npm install` at runtime). esbuild does the bundling with its own Go
 * transpiler, so the build never invokes `tsc` and is immune to TypeScript
 * version bumps. Type-checking stays a separate gate (`pnpm typecheck`, i.e.
 * `tsc --noEmit`).
 *
 * Output (all committed):
 *   dist/index.js       entry stub: enables source maps, then imports main.js
 *   dist/main.js        ESM bundle (matches root "type":"module")
 *   dist/main.js.map    source map for runtime stack traces
 *   dist/licenses.txt   aggregated third-party license texts
 *   dist/package.json   {"type":"module"} marker
 *
 * Why the stub: ncc shipped a `sourcemap-register.cjs` so action stack traces
 * point at the .ts sources. Node has that built in via
 * `process.setSourceMapsEnabled(true)`, but it only registers maps for modules
 * compiled *after* it runs — and the entry module is compiled before its own
 * code executes, so enabling it from inside the bundle is too late for the
 * bundle's own frames. The stub enables it first, then loads the bundle with a
 * *dynamic* import so the bundle is compiled with source maps already on.
 */

import { rm, writeFile } from 'node:fs/promises';
import * as esbuild from 'esbuild';
import license from 'esbuild-plugin-license';

// Own dist/ entirely so no stale artifacts (e.g. the old ncc
// sourcemap-register.cjs) linger between builds.
await rm('dist', { recursive: true, force: true });

await esbuild.build({
  entryPoints: ['src/index.ts'],
  bundle: true,
  platform: 'node',
  target: 'node24',
  format: 'esm',
  outfile: 'dist/main.js',
  sourcemap: true, // emits dist/main.js.map
  // esbuild emits a `__require` shim for the bundled CJS deps that call
  // `require(...)` (e.g. tar/undici reaching Node built-ins like `net`). In an
  // ESM output `require` is undefined, so the shim throws "Dynamic require of X
  // is not supported"; a module-scoped `require` satisfies it — the same
  // module-createRequire interop ncc's bundle used. (Source maps are turned on
  // by the dist/index.js stub, not here — see the file header.)
  banner: {
    js: [
      "import { createRequire as __createRequire } from 'node:module';",
      'const require = __createRequire(import.meta.url);',
    ].join('\n'),
  },
  legalComments: 'none', // third-party license texts go to dist/licenses.txt
  plugins: [
    license({
      // esbuild-plugin-license always prepends a banner comment to the bundle
      // (after our require shim). Its default template renders the broken
      // `/*! docverse-upload v0.0.0 |  */` (this package declares no license),
      // so give it a clean, meaningful one that points at the license file.
      banner:
        '/*! docverse-upload — bundled with esbuild; third-party licenses in dist/licenses.txt */',
      // The plugin joins a relative file with esbuild's `outdir`; we use
      // `outfile`, so name the path under dist/ explicitly.
      thirdParty: {
        output: {
          file: 'dist/licenses.txt',
          // Reproduce ncc's readable "name / license / full text" layout,
          // sorted by package name (the plugin pre-sorts the dependency list).
          template(dependencies) {
            return `${dependencies
              .map((d) => `${d.packageJson.name}\n${d.packageJson.license}\n${d.licenseText}`)
              .join('\n\n')}\n`;
          },
        },
      },
    }),
  ],
});

// Entry stub GitHub runs (action.yml `main: dist/index.js`). Enable Node's
// built-in source-map support before the bundle is compiled (see file header
// for why this must be a dynamic import), then hand off to it.
await writeFile(
  'dist/index.js',
  [
    '// Generated by scripts/build.mjs — enables source maps, then loads the bundle.',
    'process.setSourceMapsEnabled(true);',
    "await import('./main.js');",
    '',
  ].join('\n'),
);

// dist is ESM (matches the root "type":"module"); keep the explicit marker that
// ncc used to write so Node treats the bundle as a module regardless of context.
await writeFile('dist/package.json', `${JSON.stringify({ type: 'module' }, null, 2)}\n`);
